apiVersion: v1
kind: PersistentVolume
metadata:
  name: filestore-pv
spec:
  capacity:
    storage: 1Ti
  accessModes:
    - ReadWriteMany
  nfs:
    path: /vol1
    server: 10.167.132.162
  persistentVolumeReclaimPolicy: Retain
  storageClassName: filestore