apiVersion: v1
kind: PersistentVolume
metadata:
  name: otel-logs-pv
  namespace: wash-and-dry
  labels:
    name: otel-logs-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /mnt/data/otel-logs
  storageClassName: standard