apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: otel-logs-pvc
  namespace: wash-and-dry
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
  volumeName: otel-logs-pv

