apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: otel-spans-pvc
  namespace: wash-and-dry
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Ti
  storageClassName: filestore