apiVersion: apps/v1
kind: Deployment
metadata:
  name: waterfall
  namespace: wash-and-dry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: waterfall
  template:
    metadata:
      labels:
        app: waterfall
    spec:
      containers:
      - name: waterfall
        image: mreider/waterfall:8
        volumeMounts:
        - name: log-volume
          mountPath: /var/log
      volumes:
      - name: log-volume
        persistentVolumeClaim:
          claimName: otel-spans-pvc